# Generated by Django 3.1.7 on 2021-09-10 18:04

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0007_task_payment_status'),
        ('pesapal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', django.contrib.postgres.fields.citext.CICharField(choices=[('Receipt', 'Receipt'), ('Payment', 'Payment'), ('Reversal', 'Reversal'), ('Journal', 'Journal')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_task_transaction', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('memo', django.contrib.postgres.fields.citext.CICharField(max_length=400, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_creator', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work.organization')),
                ('pesapal_transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_transaction_pesapal', to='pesapal.pesapaltransaction')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work.task')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', django.contrib.postgres.fields.citext.CICharField(max_length=300, null=True)),
                ('is_balance_sheet_item', models.BooleanField(default=False)),
                ('is_income_item', models.BooleanField(default=False)),
                ('is_asset_item', models.BooleanField(default=False)),
                ('is_bank_or_cash', models.BooleanField(default=False)),
                ('is_salary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentLedgerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', django.contrib.postgres.fields.citext.CICharField(editable=False, max_length=150, unique=True)),
                ('is_balance_sheet_item', models.BooleanField(default=False)),
                ('is_income_item', models.BooleanField(default=False)),
                ('is_asset_item', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', django.contrib.postgres.fields.citext.CICharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_bank_entry', models.BooleanField(default=False)),
                ('has_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', django.contrib.postgres.fields.citext.CICharField(max_length=400, null=True)),
                ('base_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.basetransaction')),
                ('ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account', to='accounting.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationFundsWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', django.contrib.postgres.fields.citext.CICharField(choices=[('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Disbursed', 'Disbursed'), ('Pending', 'Pending'), ('Reversed', 'Reversed')], default='Pending', max_length=30)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_approved_by', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_cancelled_by', to=settings.AUTH_USER_MODEL)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_disbursed_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requested_by', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_reversed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_approve_withdrawal', 'Can approve withdrawal'), ('can_disburse_withdrawal', 'Can disburse withdrawal')),
            },
        ),
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', django.contrib.postgres.fields.citext.CICharField(max_length=300, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('is_balance_sheet_item', models.BooleanField(default=False)),
                ('is_income_item', models.BooleanField(default=False)),
                ('is_asset_item', models.BooleanField(default=False)),
                ('is_bank_or_cash', models.BooleanField(default=False)),
                ('is_salary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_group_creator', to=settings.AUTH_USER_MODEL)),
                ('parent_ledger_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.parentledgergroup')),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.ledgergroup'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_ledger', to='work.organization'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='user_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_ledger', to=settings.AUTH_USER_MODEL),
        ),
    ]
