# Generated by Django 3.1.7 on 2021-09-10 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0007_task_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesapalTransaction',
            fields=[
                ('pesapal_transaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_reference', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0)),
                ('payment_method', models.CharField(max_length=24, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work.task')),
            ],
            options={
                'unique_together': {('merchant_reference', 'pesapal_transaction')},
            },
        ),
    ]
