# Generated by Django 3.1.7 on 2021-09-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_task_amount'),
        ('pesapal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesapaltransaction',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_pesapal_transaction', to='work.task'),
        ),
    ]
