# Generated by Django 3.1.7 on 2021-08-31 07:59

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210831_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=django.contrib.postgres.fields.citext.CICharField(choices=[('', 'select profile'), ('Courzehub Staff', 'Courzehub Staff'), ('Organization Admin', 'Organization Admin'), ('System Admin', 'System Admin'), ('Worker', 'Worker')], default='Worker', max_length=100),
        ),
    ]
