# Generated by Django 3.1.7 on 2021-09-04 17:35

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerapplication',
            name='about_instructor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='mpesa_number',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='national_id',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='occupation',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
