# Generated by Django 3.1.7 on 2021-09-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210904_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerapplication',
            old_name='about_instructor',
            new_name='about_worker',
        ),
    ]
