# Generated by Django 3.1.7 on 2021-09-09 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20210909_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmissionattachment',
            name='task_submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work.tasksubmission'),
        ),
    ]
