# Generated by Django 3.1.7 on 2021-09-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20210904_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
