# Generated by Django 3.1.7 on 2021-09-09 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20210909_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tasksubmissionattachment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksubmissionattachment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
