# Generated by Django 3.1.7 on 2021-09-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_task_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_attachments', to='work.task'),
        ),
    ]
