# Generated by Django 3.1.7 on 2021-09-10 18:04

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20210909_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='payment_status',
            field=django.contrib.postgres.fields.citext.CICharField(choices=[('paid', 'paid'), ('pending', 'pending')], max_length=20, null=True),
        ),
    ]
