# Generated by Django 3.1.7 on 2021-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_task_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
