# Generated by Django 3.1.7 on 2021-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_task_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='overall_rating',
            new_name='average_overall_rating',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='courzehub_commission',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=10),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='total_cumulative_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=50),
        ),
    ]
